services:
  postgres:
    image: postgres:17

    container_name: momentum-postgres

    environment:
      POSTGRES_DB: momentum
      POSTGRES_USER: momentum
      POSTGRES_PASSWORD: momentum

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
